defmodule Adyen.Checkout.V71.CreateCheckoutSessionResponse do
  @moduledoc """
  Provides struct and type for a CreateCheckoutSessionResponse
  """

  @type t :: %__MODULE__{
          accountInfo: Adyen.Checkout.V71.AccountInfo.t() | nil,
          additionalAmount: Adyen.Checkout.V71.Amount.t() | nil,
          additionalData: map | nil,
          allowedPaymentMethods: [String.t()] | nil,
          amount: Adyen.Checkout.V71.Amount.t(),
          applicationInfo: Adyen.Checkout.V71.ApplicationInfo.t() | nil,
          authenticationData: Adyen.Checkout.V71.AuthenticationData.t() | nil,
          billingAddress: Adyen.Checkout.V71.BillingAddress.t() | nil,
          blockedPaymentMethods: [String.t()] | nil,
          captureDelayHours: integer | nil,
          channel: String.t() | nil,
          company: Adyen.Checkout.V71.Company.t() | nil,
          countryCode: String.t() | nil,
          dateOfBirth: DateTime.t() | nil,
          deliverAt: DateTime.t() | nil,
          deliveryAddress: Adyen.Checkout.V71.DeliveryAddress.t() | nil,
          enableOneClick: boolean | nil,
          enablePayOut: boolean | nil,
          enableRecurring: boolean | nil,
          expiresAt: DateTime.t(),
          fundOrigin: Adyen.Checkout.V71.FundOrigin.t() | nil,
          fundRecipient: Adyen.Checkout.V71.FundRecipient.t() | nil,
          id: String.t(),
          installmentOptions: map | nil,
          lineItems: [Adyen.Checkout.V71.LineItem.t()] | nil,
          mandate: Adyen.Checkout.V71.Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          metadata: map | nil,
          mode: String.t() | nil,
          mpiData: Adyen.Checkout.V71.ThreeDSecureData.t() | nil,
          platformChargebackLogic: Adyen.Checkout.V71.PlatformChargebackLogic.t() | nil,
          recurringExpiry: String.t() | nil,
          recurringFrequency: String.t() | nil,
          recurringProcessingModel: String.t() | nil,
          redirectFromIssuerMethod: String.t() | nil,
          redirectToIssuerMethod: String.t() | nil,
          reference: String.t(),
          returnUrl: String.t(),
          riskData: Adyen.Checkout.V71.RiskData.t() | nil,
          sessionData: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: Adyen.Checkout.V71.ShopperName.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          showInstallmentAmount: boolean | nil,
          showRemovePaymentMethodButton: boolean | nil,
          socialSecurityNumber: String.t() | nil,
          splitCardFundingSources: boolean | nil,
          splits: [Adyen.Checkout.V71.Split.t()] | nil,
          store: String.t() | nil,
          storeFiltrationMode: String.t() | nil,
          storePaymentMethod: boolean | nil,
          storePaymentMethodMode: String.t() | nil,
          telephoneNumber: String.t() | nil,
          themeId: String.t() | nil,
          threeDS2RequestData: Adyen.Checkout.V71.CheckoutSessionThreeDs2RequestData.t() | nil,
          threeDSAuthenticationOnly: boolean | nil,
          trustedShopper: boolean | nil,
          url: String.t() | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :allowedPaymentMethods,
    :amount,
    :applicationInfo,
    :authenticationData,
    :billingAddress,
    :blockedPaymentMethods,
    :captureDelayHours,
    :channel,
    :company,
    :countryCode,
    :dateOfBirth,
    :deliverAt,
    :deliveryAddress,
    :enableOneClick,
    :enablePayOut,
    :enableRecurring,
    :expiresAt,
    :fundOrigin,
    :fundRecipient,
    :id,
    :installmentOptions,
    :lineItems,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :metadata,
    :mode,
    :mpiData,
    :platformChargebackLogic,
    :recurringExpiry,
    :recurringFrequency,
    :recurringProcessingModel,
    :redirectFromIssuerMethod,
    :redirectToIssuerMethod,
    :reference,
    :returnUrl,
    :riskData,
    :sessionData,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :showInstallmentAmount,
    :showRemovePaymentMethodButton,
    :socialSecurityNumber,
    :splitCardFundingSources,
    :splits,
    :store,
    :storeFiltrationMode,
    :storePaymentMethod,
    :storePaymentMethodMode,
    :telephoneNumber,
    :themeId,
    :threeDS2RequestData,
    :threeDSAuthenticationOnly,
    :trustedShopper,
    :url
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {Adyen.Checkout.V71.AccountInfo, :t},
      additionalAmount: {Adyen.Checkout.V71.Amount, :t},
      additionalData: :map,
      allowedPaymentMethods: [:string],
      amount: {Adyen.Checkout.V71.Amount, :t},
      applicationInfo: {Adyen.Checkout.V71.ApplicationInfo, :t},
      authenticationData: {Adyen.Checkout.V71.AuthenticationData, :t},
      billingAddress: {Adyen.Checkout.V71.BillingAddress, :t},
      blockedPaymentMethods: [:string],
      captureDelayHours: {:integer, "int32"},
      channel: {:enum, ["iOS", "Android", "Web"]},
      company: {Adyen.Checkout.V71.Company, :t},
      countryCode: :string,
      dateOfBirth: {:string, "date-time"},
      deliverAt: {:string, "date-time"},
      deliveryAddress: {Adyen.Checkout.V71.DeliveryAddress, :t},
      enableOneClick: :boolean,
      enablePayOut: :boolean,
      enableRecurring: :boolean,
      expiresAt: {:string, "date-time"},
      fundOrigin: {Adyen.Checkout.V71.FundOrigin, :t},
      fundRecipient: {Adyen.Checkout.V71.FundRecipient, :t},
      id: :string,
      installmentOptions: :map,
      lineItems: [{Adyen.Checkout.V71.LineItem, :t}],
      mandate: {Adyen.Checkout.V71.Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      metadata: :map,
      mode: {:enum, ["embedded", "hosted"]},
      mpiData: {Adyen.Checkout.V71.ThreeDSecureData, :t},
      platformChargebackLogic: {Adyen.Checkout.V71.PlatformChargebackLogic, :t},
      recurringExpiry: :string,
      recurringFrequency: :string,
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      redirectFromIssuerMethod: :string,
      redirectToIssuerMethod: :string,
      reference: :string,
      returnUrl: :string,
      riskData: {Adyen.Checkout.V71.RiskData, :t},
      sessionData: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {Adyen.Checkout.V71.ShopperName, :t},
      shopperReference: :string,
      shopperStatement: :string,
      showInstallmentAmount: :boolean,
      showRemovePaymentMethodButton: :boolean,
      socialSecurityNumber: :string,
      splitCardFundingSources: :boolean,
      splits: [{Adyen.Checkout.V71.Split, :t}],
      store: :string,
      storeFiltrationMode: {:enum, ["exclusive", "inclusive", "skipFilter"]},
      storePaymentMethod: :boolean,
      storePaymentMethodMode: {:enum, ["askForConsent", "disabled", "enabled"]},
      telephoneNumber: :string,
      themeId: :string,
      threeDS2RequestData: {Adyen.Checkout.V71.CheckoutSessionThreeDs2RequestData, :t},
      threeDSAuthenticationOnly: :boolean,
      trustedShopper: :boolean,
      url: :string
    ]
  end
end
