defmodule AdyenEx.Checkout.V72.Donations do
  @moduledoc """
  Provides API endpoints related to donations
  """

  @default_client AdyenEx.Client

  @doc """
  Get a list of donation campaigns.

  Queries the available donation campaigns for a donation based on the donation context (like merchant account, currency, and locale). The response contains active donation campaigns.

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec post_donation_campaigns(
          body :: AdyenEx.Checkout.V72.DonationCampaignsRequest.t(),
          opts :: keyword
        ) ::
          {:ok, AdyenEx.Checkout.V72.DonationCampaignsResponse.t()}
          | {:error, AdyenEx.Checkout.V72.ServiceError.t()}
  def post_donation_campaigns(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {AdyenEx.Checkout.V72.Donations, :post_donation_campaigns},
      url: "/donationCampaigns",
      body: body,
      method: :post,
      request: [{"application/json", {AdyenEx.Checkout.V72.DonationCampaignsRequest, :t}}],
      response: [
        {200, {AdyenEx.Checkout.V72.DonationCampaignsResponse, :t}},
        {400, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {401, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {403, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {422, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {500, {AdyenEx.Checkout.V72.ServiceError, :t}}
      ],
      opts: opts
    })
  end

  @doc """
  Make a donation

  Takes in the donation token generated by the `/payments` request and uses it to make the donation.

  For more information, see [Donations](https://docs.adyen.com/online-payments/donations).

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec post_donations(body :: AdyenEx.Checkout.V72.DonationPaymentRequest.t(), opts :: keyword) ::
          {:ok, AdyenEx.Checkout.V72.DonationPaymentResponse.t()}
          | {:error, AdyenEx.Checkout.V72.ServiceError.t()}
  def post_donations(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {AdyenEx.Checkout.V72.Donations, :post_donations},
      url: "/donations",
      body: body,
      method: :post,
      request: [{"application/json", {AdyenEx.Checkout.V72.DonationPaymentRequest, :t}}],
      response: [
        {200, {AdyenEx.Checkout.V72.DonationPaymentResponse, :t}},
        {400, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {401, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {403, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {422, {AdyenEx.Checkout.V72.ServiceError, :t}},
        {500, {AdyenEx.Checkout.V72.ServiceError, :t}}
      ],
      opts: opts
    })
  end
end
