defmodule AdyenEx.Checkout.V53.DonationPaymentRequest do
  @moduledoc """
  Provides struct and type for a DonationPaymentRequest
  """

  @type t :: %__MODULE__{
          accountInfo: AdyenEx.Checkout.V53.AccountInfo.t() | nil,
          additionalAmount: AdyenEx.Checkout.V53.Amount.t() | nil,
          additionalData: map | nil,
          allowedPaymentMethods: [String.t()] | nil,
          amount: AdyenEx.Checkout.V53.Amount.t(),
          applicationInfo: AdyenEx.Checkout.V53.ApplicationInfo.t() | nil,
          billingAddress: AdyenEx.Checkout.V53.BillingAddress.t() | nil,
          blockedPaymentMethods: [String.t()] | nil,
          browserInfo: AdyenEx.Checkout.V53.BrowserInfo.t() | nil,
          captureDelayHours: integer | nil,
          channel: String.t() | nil,
          checkoutAttemptId: String.t() | nil,
          company: AdyenEx.Checkout.V53.Company.t() | nil,
          conversionId: String.t() | nil,
          countryCode: String.t() | nil,
          dateOfBirth: DateTime.t() | nil,
          dccQuote: AdyenEx.Checkout.V53.ForexQuote.t() | nil,
          deliveryAddress: AdyenEx.Checkout.V53.DeliveryAddress.t() | nil,
          deliveryDate: DateTime.t() | nil,
          deviceFingerprint: String.t() | nil,
          donationAccount: String.t() | nil,
          donationOriginalPspReference: String.t() | nil,
          donationToken: String.t() | nil,
          enableOneClick: boolean | nil,
          enablePayOut: boolean | nil,
          enableRealTimeUpdate: boolean | nil,
          enableRecurring: boolean | nil,
          entityType: String.t() | nil,
          fraudOffset: integer | nil,
          fundOrigin: AdyenEx.Checkout.V53.FundOrigin.t() | nil,
          fundRecipient: AdyenEx.Checkout.V53.FundRecipient.t() | nil,
          fundingSource: String.t() | nil,
          installments: AdyenEx.Checkout.V53.Installments.t() | nil,
          lineItems: [AdyenEx.Checkout.V53.LineItem.t()] | nil,
          mandate: AdyenEx.Checkout.V53.Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          merchantRiskIndicator: AdyenEx.Checkout.V53.MerchantRiskIndicator.t() | nil,
          metadata: map | nil,
          mpiData: AdyenEx.Checkout.V53.ThreeDSecureData.t() | nil,
          order: AdyenEx.Checkout.V53.EncryptedOrderData.t() | nil,
          orderReference: String.t() | nil,
          origin: String.t() | nil,
          paymentMethod:
            AdyenEx.Checkout.V53.ApplePayDonations.t()
            | AdyenEx.Checkout.V53.CardDonations.t()
            | AdyenEx.Checkout.V53.GooglePayDonations.t()
            | AdyenEx.Checkout.V53.IdealDonations.t()
            | AdyenEx.Checkout.V53.PayWithGoogleDonations.t()
            | AdyenEx.Checkout.V53.SepaDirectDebitDonations.t()
            | nil,
          recurringExpiry: String.t() | nil,
          recurringFrequency: String.t() | nil,
          recurringProcessingModel: String.t() | nil,
          redirectFromIssuerMethod: String.t() | nil,
          redirectToIssuerMethod: String.t() | nil,
          reference: String.t(),
          returnUrl: String.t(),
          riskData: AdyenEx.Checkout.V53.RiskData.t() | nil,
          selectedRecurringDetailReference: String.t() | nil,
          sessionValidity: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: AdyenEx.Checkout.V53.ShopperName.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          socialSecurityNumber: String.t() | nil,
          splits: [AdyenEx.Checkout.V53.Split.t()] | nil,
          store: String.t() | nil,
          storePaymentMethod: boolean | nil,
          telephoneNumber: String.t() | nil,
          threeDS2RequestData: AdyenEx.Checkout.V53.ThreeDs2RequestFields.t() | nil,
          threeDSAuthenticationOnly: boolean | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :allowedPaymentMethods,
    :amount,
    :applicationInfo,
    :billingAddress,
    :blockedPaymentMethods,
    :browserInfo,
    :captureDelayHours,
    :channel,
    :checkoutAttemptId,
    :company,
    :conversionId,
    :countryCode,
    :dateOfBirth,
    :dccQuote,
    :deliveryAddress,
    :deliveryDate,
    :deviceFingerprint,
    :donationAccount,
    :donationOriginalPspReference,
    :donationToken,
    :enableOneClick,
    :enablePayOut,
    :enableRealTimeUpdate,
    :enableRecurring,
    :entityType,
    :fraudOffset,
    :fundOrigin,
    :fundRecipient,
    :fundingSource,
    :installments,
    :lineItems,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :merchantRiskIndicator,
    :metadata,
    :mpiData,
    :order,
    :orderReference,
    :origin,
    :paymentMethod,
    :recurringExpiry,
    :recurringFrequency,
    :recurringProcessingModel,
    :redirectFromIssuerMethod,
    :redirectToIssuerMethod,
    :reference,
    :returnUrl,
    :riskData,
    :selectedRecurringDetailReference,
    :sessionValidity,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :socialSecurityNumber,
    :splits,
    :store,
    :storePaymentMethod,
    :telephoneNumber,
    :threeDS2RequestData,
    :threeDSAuthenticationOnly,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {AdyenEx.Checkout.V53.AccountInfo, :t},
      additionalAmount: {AdyenEx.Checkout.V53.Amount, :t},
      additionalData: :map,
      allowedPaymentMethods: [:string],
      amount: {AdyenEx.Checkout.V53.Amount, :t},
      applicationInfo: {AdyenEx.Checkout.V53.ApplicationInfo, :t},
      billingAddress: {AdyenEx.Checkout.V53.BillingAddress, :t},
      blockedPaymentMethods: [:string],
      browserInfo: {AdyenEx.Checkout.V53.BrowserInfo, :t},
      captureDelayHours: {:integer, "int32"},
      channel: {:enum, ["iOS", "Android", "Web"]},
      checkoutAttemptId: :string,
      company: {AdyenEx.Checkout.V53.Company, :t},
      conversionId: :string,
      countryCode: :string,
      dateOfBirth: {:string, "date-time"},
      dccQuote: {AdyenEx.Checkout.V53.ForexQuote, :t},
      deliveryAddress: {AdyenEx.Checkout.V53.DeliveryAddress, :t},
      deliveryDate: {:string, "date-time"},
      deviceFingerprint: :string,
      donationAccount: :string,
      donationOriginalPspReference: :string,
      donationToken: :string,
      enableOneClick: :boolean,
      enablePayOut: :boolean,
      enableRealTimeUpdate: :boolean,
      enableRecurring: :boolean,
      entityType: {:enum, ["NaturalPerson", "CompanyName"]},
      fraudOffset: {:integer, "int32"},
      fundOrigin: {AdyenEx.Checkout.V53.FundOrigin, :t},
      fundRecipient: {AdyenEx.Checkout.V53.FundRecipient, :t},
      fundingSource: {:const, "debit"},
      installments: {AdyenEx.Checkout.V53.Installments, :t},
      lineItems: [{AdyenEx.Checkout.V53.LineItem, :t}],
      mandate: {AdyenEx.Checkout.V53.Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      merchantRiskIndicator: {AdyenEx.Checkout.V53.MerchantRiskIndicator, :t},
      metadata: :map,
      mpiData: {AdyenEx.Checkout.V53.ThreeDSecureData, :t},
      order: {AdyenEx.Checkout.V53.EncryptedOrderData, :t},
      orderReference: :string,
      origin: :string,
      paymentMethod:
        {:union,
         [
           {AdyenEx.Checkout.V53.ApplePayDonations, :t},
           {AdyenEx.Checkout.V53.CardDonations, :t},
           {AdyenEx.Checkout.V53.GooglePayDonations, :t},
           {AdyenEx.Checkout.V53.IdealDonations, :t},
           {AdyenEx.Checkout.V53.PayWithGoogleDonations, :t},
           {AdyenEx.Checkout.V53.SepaDirectDebitDonations, :t}
         ]},
      recurringExpiry: :string,
      recurringFrequency: :string,
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      redirectFromIssuerMethod: :string,
      redirectToIssuerMethod: :string,
      reference: :string,
      returnUrl: :string,
      riskData: {AdyenEx.Checkout.V53.RiskData, :t},
      selectedRecurringDetailReference: :string,
      sessionValidity: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {AdyenEx.Checkout.V53.ShopperName, :t},
      shopperReference: :string,
      shopperStatement: :string,
      socialSecurityNumber: :string,
      splits: [{AdyenEx.Checkout.V53.Split, :t}],
      store: :string,
      storePaymentMethod: :boolean,
      telephoneNumber: :string,
      threeDS2RequestData: {AdyenEx.Checkout.V53.ThreeDs2RequestFields, :t},
      threeDSAuthenticationOnly: :boolean,
      trustedShopper: :boolean
    ]
  end
end
