defmodule AdyenEx.Checkout.V66.Donations do
  @moduledoc """
  Provides API endpoint related to donations
  """

  @default_client AdyenEx.Client

  @doc """
  Make a donation

  Takes in the donation token generated by the `/payments` request and uses it to make the donation.

  For more information, see [Donations](https://docs.adyen.com/online-payments/donations).

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec post_donations(body :: AdyenEx.Checkout.V66.DonationPaymentRequest.t(), opts :: keyword) ::
          {:ok, AdyenEx.Checkout.V66.DonationPaymentResponse.t()}
          | {:error, AdyenEx.Checkout.V66.ServiceError.t()}
  def post_donations(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {AdyenEx.Checkout.V66.Donations, :post_donations},
      url: "/donations",
      body: body,
      method: :post,
      request: [{"application/json", {AdyenEx.Checkout.V66.DonationPaymentRequest, :t}}],
      response: [
        {200, {AdyenEx.Checkout.V66.DonationPaymentResponse, :t}},
        {400, {AdyenEx.Checkout.V66.ServiceError, :t}},
        {401, {AdyenEx.Checkout.V66.ServiceError, :t}},
        {403, {AdyenEx.Checkout.V66.ServiceError, :t}},
        {422, {AdyenEx.Checkout.V66.ServiceError, :t}},
        {500, {AdyenEx.Checkout.V66.ServiceError, :t}}
      ],
      opts: opts
    })
  end
end
