defmodule Adyen.Checkout.V49.DonationPaymentRequest do
  @moduledoc """
  Provides struct and type for a DonationPaymentRequest
  """

  @type t :: %__MODULE__{
          accountInfo: Adyen.Checkout.V49.AccountInfo.t() | nil,
          additionalAmount: Adyen.Checkout.V49.Amount.t() | nil,
          additionalData: map | nil,
          allowedPaymentMethods: [String.t()] | nil,
          amount: Adyen.Checkout.V49.Amount.t(),
          applicationInfo: Adyen.Checkout.V49.ApplicationInfo.t() | nil,
          billingAddress: Adyen.Checkout.V49.BillingAddress.t() | nil,
          blockedPaymentMethods: [String.t()] | nil,
          browserInfo: Adyen.Checkout.V49.BrowserInfo.t() | nil,
          captureDelayHours: integer | nil,
          channel: String.t() | nil,
          checkoutAttemptId: String.t() | nil,
          company: Adyen.Checkout.V49.Company.t() | nil,
          conversionId: String.t() | nil,
          countryCode: String.t() | nil,
          dateOfBirth: DateTime.t() | nil,
          dccQuote: Adyen.Checkout.V49.ForexQuote.t() | nil,
          deliveryAddress: Adyen.Checkout.V49.DeliveryAddress.t() | nil,
          deliveryDate: DateTime.t() | nil,
          deviceFingerprint: String.t() | nil,
          donationAccount: String.t() | nil,
          donationOriginalPspReference: String.t() | nil,
          donationToken: String.t() | nil,
          enableOneClick: boolean | nil,
          enablePayOut: boolean | nil,
          enableRecurring: boolean | nil,
          entityType: String.t() | nil,
          fraudOffset: integer | nil,
          fundOrigin: Adyen.Checkout.V49.FundOrigin.t() | nil,
          fundRecipient: Adyen.Checkout.V49.FundRecipient.t() | nil,
          installments: Adyen.Checkout.V49.Installments.t() | nil,
          lineItems: [Adyen.Checkout.V49.LineItem.t()] | nil,
          mandate: Adyen.Checkout.V49.Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          merchantRiskIndicator: Adyen.Checkout.V49.MerchantRiskIndicator.t() | nil,
          metadata: map | nil,
          mpiData: Adyen.Checkout.V49.ThreeDSecureData.t() | nil,
          order: Adyen.Checkout.V49.EncryptedOrderData.t() | nil,
          orderReference: String.t() | nil,
          origin: String.t() | nil,
          paymentMethod:
            Adyen.Checkout.V49.ApplePayDonations.t()
            | Adyen.Checkout.V49.CardDonations.t()
            | Adyen.Checkout.V49.GooglePayDonations.t()
            | Adyen.Checkout.V49.IdealDonations.t()
            | Adyen.Checkout.V49.PayWithGoogleDonations.t()
            | nil,
          recurringExpiry: String.t() | nil,
          recurringFrequency: String.t() | nil,
          recurringProcessingModel: String.t() | nil,
          redirectFromIssuerMethod: String.t() | nil,
          redirectToIssuerMethod: String.t() | nil,
          reference: String.t(),
          returnUrl: String.t(),
          riskData: Adyen.Checkout.V49.RiskData.t() | nil,
          selectedRecurringDetailReference: String.t() | nil,
          sessionValidity: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: Adyen.Checkout.V49.ShopperName.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          socialSecurityNumber: String.t() | nil,
          splits: [Adyen.Checkout.V49.Split.t()] | nil,
          store: String.t() | nil,
          storePaymentMethod: boolean | nil,
          telephoneNumber: String.t() | nil,
          threeDS2RequestData: Adyen.Checkout.V49.ThreeDs2RequestFields.t() | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :allowedPaymentMethods,
    :amount,
    :applicationInfo,
    :billingAddress,
    :blockedPaymentMethods,
    :browserInfo,
    :captureDelayHours,
    :channel,
    :checkoutAttemptId,
    :company,
    :conversionId,
    :countryCode,
    :dateOfBirth,
    :dccQuote,
    :deliveryAddress,
    :deliveryDate,
    :deviceFingerprint,
    :donationAccount,
    :donationOriginalPspReference,
    :donationToken,
    :enableOneClick,
    :enablePayOut,
    :enableRecurring,
    :entityType,
    :fraudOffset,
    :fundOrigin,
    :fundRecipient,
    :installments,
    :lineItems,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :merchantRiskIndicator,
    :metadata,
    :mpiData,
    :order,
    :orderReference,
    :origin,
    :paymentMethod,
    :recurringExpiry,
    :recurringFrequency,
    :recurringProcessingModel,
    :redirectFromIssuerMethod,
    :redirectToIssuerMethod,
    :reference,
    :returnUrl,
    :riskData,
    :selectedRecurringDetailReference,
    :sessionValidity,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :socialSecurityNumber,
    :splits,
    :store,
    :storePaymentMethod,
    :telephoneNumber,
    :threeDS2RequestData,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {Adyen.Checkout.V49.AccountInfo, :t},
      additionalAmount: {Adyen.Checkout.V49.Amount, :t},
      additionalData: :map,
      allowedPaymentMethods: [:string],
      amount: {Adyen.Checkout.V49.Amount, :t},
      applicationInfo: {Adyen.Checkout.V49.ApplicationInfo, :t},
      billingAddress: {Adyen.Checkout.V49.BillingAddress, :t},
      blockedPaymentMethods: [:string],
      browserInfo: {Adyen.Checkout.V49.BrowserInfo, :t},
      captureDelayHours: {:integer, "int32"},
      channel: {:enum, ["iOS", "Android", "Web"]},
      checkoutAttemptId: :string,
      company: {Adyen.Checkout.V49.Company, :t},
      conversionId: :string,
      countryCode: :string,
      dateOfBirth: {:string, "date-time"},
      dccQuote: {Adyen.Checkout.V49.ForexQuote, :t},
      deliveryAddress: {Adyen.Checkout.V49.DeliveryAddress, :t},
      deliveryDate: {:string, "date-time"},
      deviceFingerprint: :string,
      donationAccount: :string,
      donationOriginalPspReference: :string,
      donationToken: :string,
      enableOneClick: :boolean,
      enablePayOut: :boolean,
      enableRecurring: :boolean,
      entityType: {:enum, ["NaturalPerson", "CompanyName"]},
      fraudOffset: {:integer, "int32"},
      fundOrigin: {Adyen.Checkout.V49.FundOrigin, :t},
      fundRecipient: {Adyen.Checkout.V49.FundRecipient, :t},
      installments: {Adyen.Checkout.V49.Installments, :t},
      lineItems: [{Adyen.Checkout.V49.LineItem, :t}],
      mandate: {Adyen.Checkout.V49.Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      merchantRiskIndicator: {Adyen.Checkout.V49.MerchantRiskIndicator, :t},
      metadata: :map,
      mpiData: {Adyen.Checkout.V49.ThreeDSecureData, :t},
      order: {Adyen.Checkout.V49.EncryptedOrderData, :t},
      orderReference: :string,
      origin: :string,
      paymentMethod:
        {:union,
         [
           {Adyen.Checkout.V49.ApplePayDonations, :t},
           {Adyen.Checkout.V49.CardDonations, :t},
           {Adyen.Checkout.V49.GooglePayDonations, :t},
           {Adyen.Checkout.V49.IdealDonations, :t},
           {Adyen.Checkout.V49.PayWithGoogleDonations, :t}
         ]},
      recurringExpiry: :string,
      recurringFrequency: :string,
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      redirectFromIssuerMethod: :string,
      redirectToIssuerMethod: :string,
      reference: :string,
      returnUrl: :string,
      riskData: {Adyen.Checkout.V49.RiskData, :t},
      selectedRecurringDetailReference: :string,
      sessionValidity: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {Adyen.Checkout.V49.ShopperName, :t},
      shopperReference: :string,
      shopperStatement: :string,
      socialSecurityNumber: :string,
      splits: [{Adyen.Checkout.V49.Split, :t}],
      store: :string,
      storePaymentMethod: :boolean,
      telephoneNumber: :string,
      threeDS2RequestData: {Adyen.Checkout.V49.ThreeDs2RequestFields, :t},
      trustedShopper: :boolean
    ]
  end
end
