defmodule AdyenEx.Payment.V46.PaymentRequest do
  @moduledoc """
  Provides struct and type for a PaymentRequest
  """

  @type t :: %__MODULE__{
          accountInfo: AdyenEx.Payment.V46.AccountInfo.t() | nil,
          additionalAmount: AdyenEx.Payment.V46.Amount.t() | nil,
          additionalData: map | nil,
          amount: AdyenEx.Payment.V46.Amount.t(),
          applicationInfo: AdyenEx.Payment.V46.ApplicationInfo.t() | nil,
          bankAccount: AdyenEx.Payment.V46.BankAccount.t() | nil,
          billingAddress: AdyenEx.Payment.V46.Address.t() | nil,
          browserInfo: AdyenEx.Payment.V46.BrowserInfo.t() | nil,
          captureDelayHours: integer | nil,
          card: AdyenEx.Payment.V46.Card.t() | nil,
          dateOfBirth: Date.t() | nil,
          dccQuote: AdyenEx.Payment.V46.ForexQuote.t() | nil,
          deliveryAddress: AdyenEx.Payment.V46.Address.t() | nil,
          deliveryDate: DateTime.t() | nil,
          deviceFingerprint: String.t() | nil,
          entityType: String.t() | nil,
          fraudOffset: integer | nil,
          installments: AdyenEx.Payment.V46.Installments.t() | nil,
          mandate: AdyenEx.Payment.V46.Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          merchantRiskIndicator: AdyenEx.Payment.V46.MerchantRiskIndicator.t() | nil,
          metadata: map | nil,
          mpiData: AdyenEx.Payment.V46.ThreeDSecureData.t() | nil,
          nationality: String.t() | nil,
          orderReference: String.t() | nil,
          recurring: AdyenEx.Payment.V46.Recurring.t() | nil,
          recurringProcessingModel: String.t() | nil,
          reference: String.t(),
          selectedBrand: String.t() | nil,
          selectedRecurringDetailReference: String.t() | nil,
          sessionId: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: AdyenEx.Payment.V46.Name.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          socialSecurityNumber: String.t() | nil,
          splits: [AdyenEx.Payment.V46.Split.t()] | nil,
          store: String.t() | nil,
          telephoneNumber: String.t() | nil,
          threeDS2RequestData: AdyenEx.Payment.V46.ThreeDs2RequestData.t() | nil,
          totalsGroup: String.t() | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :amount,
    :applicationInfo,
    :bankAccount,
    :billingAddress,
    :browserInfo,
    :captureDelayHours,
    :card,
    :dateOfBirth,
    :dccQuote,
    :deliveryAddress,
    :deliveryDate,
    :deviceFingerprint,
    :entityType,
    :fraudOffset,
    :installments,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :merchantRiskIndicator,
    :metadata,
    :mpiData,
    :nationality,
    :orderReference,
    :recurring,
    :recurringProcessingModel,
    :reference,
    :selectedBrand,
    :selectedRecurringDetailReference,
    :sessionId,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :socialSecurityNumber,
    :splits,
    :store,
    :telephoneNumber,
    :threeDS2RequestData,
    :totalsGroup,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {AdyenEx.Payment.V46.AccountInfo, :t},
      additionalAmount: {AdyenEx.Payment.V46.Amount, :t},
      additionalData: :map,
      amount: {AdyenEx.Payment.V46.Amount, :t},
      applicationInfo: {AdyenEx.Payment.V46.ApplicationInfo, :t},
      bankAccount: {AdyenEx.Payment.V46.BankAccount, :t},
      billingAddress: {AdyenEx.Payment.V46.Address, :t},
      browserInfo: {AdyenEx.Payment.V46.BrowserInfo, :t},
      captureDelayHours: {:integer, "int32"},
      card: {AdyenEx.Payment.V46.Card, :t},
      dateOfBirth: {:string, "date"},
      dccQuote: {AdyenEx.Payment.V46.ForexQuote, :t},
      deliveryAddress: {AdyenEx.Payment.V46.Address, :t},
      deliveryDate: {:string, "date-time"},
      deviceFingerprint: :string,
      entityType: {:enum, ["NaturalPerson", "CompanyName"]},
      fraudOffset: {:integer, "int32"},
      installments: {AdyenEx.Payment.V46.Installments, :t},
      mandate: {AdyenEx.Payment.V46.Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      merchantRiskIndicator: {AdyenEx.Payment.V46.MerchantRiskIndicator, :t},
      metadata: :map,
      mpiData: {AdyenEx.Payment.V46.ThreeDSecureData, :t},
      nationality: :string,
      orderReference: :string,
      recurring: {AdyenEx.Payment.V46.Recurring, :t},
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      reference: :string,
      selectedBrand: :string,
      selectedRecurringDetailReference: :string,
      sessionId: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {AdyenEx.Payment.V46.Name, :t},
      shopperReference: :string,
      shopperStatement: :string,
      socialSecurityNumber: :string,
      splits: [{AdyenEx.Payment.V46.Split, :t}],
      store: :string,
      telephoneNumber: :string,
      threeDS2RequestData: {AdyenEx.Payment.V46.ThreeDs2RequestData, :t},
      totalsGroup: :string,
      trustedShopper: :boolean
    ]
  end
end
