defmodule AdyenEx.Management.V1.PaymentMethodSetupInfo do
  @moduledoc """
  Provides struct and type for a PaymentMethodSetupInfo
  """

  @type t :: %__MODULE__{
          accel: AdyenEx.Management.V1.AccelInfo.t() | nil,
          affirm: AdyenEx.Management.V1.AffirmInfo.t() | nil,
          afterpayTouch: AdyenEx.Management.V1.AfterpayTouchInfo.t() | nil,
          alipayPlus: AdyenEx.Management.V1.AlipayPlusInfo.t() | nil,
          amex: AdyenEx.Management.V1.AmexInfo.t() | nil,
          applePay: AdyenEx.Management.V1.ApplePayInfo.t() | nil,
          bcmc: AdyenEx.Management.V1.BcmcInfo.t() | nil,
          businessLineId: String.t() | nil,
          carnet: AdyenEx.Management.V1.CarnetInfo.t() | nil,
          cartesBancaires: AdyenEx.Management.V1.CartesBancairesInfo.t() | nil,
          clearpay: AdyenEx.Management.V1.ClearpayInfo.t() | nil,
          countries: [String.t()] | nil,
          cup: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          currencies: [String.t()] | nil,
          customRoutingFlags: [String.t()] | nil,
          diners: AdyenEx.Management.V1.DinersInfo.t() | nil,
          discover: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          eft_directdebit_CA: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          eftpos_australia: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          girocard: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          givex: AdyenEx.Management.V1.GivexInfo.t() | nil,
          googlePay: AdyenEx.Management.V1.GooglePayInfo.t() | nil,
          ideal: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          interac_card: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          jcb: AdyenEx.Management.V1.JCBInfo.t() | nil,
          klarna: AdyenEx.Management.V1.KlarnaInfo.t() | nil,
          maestro: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          maestro_usa: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          mc: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          mealVoucher_FR: AdyenEx.Management.V1.MealVoucherFRInfo.t() | nil,
          nyce: AdyenEx.Management.V1.NyceInfo.t() | nil,
          paybybank_plaid: AdyenEx.Management.V1.PayByBankPlaidInfo.t() | nil,
          payme: AdyenEx.Management.V1.PayMeInfo.t() | nil,
          paypal: AdyenEx.Management.V1.PayPalInfo.t() | nil,
          payto: AdyenEx.Management.V1.PayToInfo.t() | nil,
          pulse: AdyenEx.Management.V1.PulseInfo.t() | nil,
          reference: String.t() | nil,
          sepadirectdebit: AdyenEx.Management.V1.SepaDirectDebitInfo.t() | nil,
          shopperInteraction: String.t() | nil,
          sodexo: AdyenEx.Management.V1.SodexoInfo.t() | nil,
          sofort: AdyenEx.Management.V1.SofortInfo.t() | nil,
          star: AdyenEx.Management.V1.StarInfo.t() | nil,
          storeId: String.t() | nil,
          svs: AdyenEx.Management.V1.SvsInfo.t() | nil,
          swish: AdyenEx.Management.V1.SwishInfo.t() | nil,
          ticket: AdyenEx.Management.V1.TicketInfo.t() | nil,
          twint: AdyenEx.Management.V1.TwintInfo.t() | nil,
          type: String.t(),
          valuelink: AdyenEx.Management.V1.ValuelinkInfo.t() | nil,
          vipps: AdyenEx.Management.V1.VippsInfo.t() | nil,
          visa: AdyenEx.Management.V1.GenericPmWithTdiInfo.t() | nil,
          wechatpay: AdyenEx.Management.V1.WeChatPayInfo.t() | nil,
          wechatpay_pos: AdyenEx.Management.V1.WeChatPayPosInfo.t() | nil
        }

  defstruct [
    :accel,
    :affirm,
    :afterpayTouch,
    :alipayPlus,
    :amex,
    :applePay,
    :bcmc,
    :businessLineId,
    :carnet,
    :cartesBancaires,
    :clearpay,
    :countries,
    :cup,
    :currencies,
    :customRoutingFlags,
    :diners,
    :discover,
    :eft_directdebit_CA,
    :eftpos_australia,
    :girocard,
    :givex,
    :googlePay,
    :ideal,
    :interac_card,
    :jcb,
    :klarna,
    :maestro,
    :maestro_usa,
    :mc,
    :mealVoucher_FR,
    :nyce,
    :paybybank_plaid,
    :payme,
    :paypal,
    :payto,
    :pulse,
    :reference,
    :sepadirectdebit,
    :shopperInteraction,
    :sodexo,
    :sofort,
    :star,
    :storeId,
    :svs,
    :swish,
    :ticket,
    :twint,
    :type,
    :valuelink,
    :vipps,
    :visa,
    :wechatpay,
    :wechatpay_pos
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accel: {AdyenEx.Management.V1.AccelInfo, :t},
      affirm: {AdyenEx.Management.V1.AffirmInfo, :t},
      afterpayTouch: {AdyenEx.Management.V1.AfterpayTouchInfo, :t},
      alipayPlus: {AdyenEx.Management.V1.AlipayPlusInfo, :t},
      amex: {AdyenEx.Management.V1.AmexInfo, :t},
      applePay: {AdyenEx.Management.V1.ApplePayInfo, :t},
      bcmc: {AdyenEx.Management.V1.BcmcInfo, :t},
      businessLineId: :string,
      carnet: {AdyenEx.Management.V1.CarnetInfo, :t},
      cartesBancaires: {AdyenEx.Management.V1.CartesBancairesInfo, :t},
      clearpay: {AdyenEx.Management.V1.ClearpayInfo, :t},
      countries: [:string],
      cup: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      currencies: [:string],
      customRoutingFlags: [:string],
      diners: {AdyenEx.Management.V1.DinersInfo, :t},
      discover: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      eft_directdebit_CA: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      eftpos_australia: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      girocard: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      givex: {AdyenEx.Management.V1.GivexInfo, :t},
      googlePay: {AdyenEx.Management.V1.GooglePayInfo, :t},
      ideal: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      interac_card: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      jcb: {AdyenEx.Management.V1.JCBInfo, :t},
      klarna: {AdyenEx.Management.V1.KlarnaInfo, :t},
      maestro: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      maestro_usa: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      mc: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      mealVoucher_FR: {AdyenEx.Management.V1.MealVoucherFRInfo, :t},
      nyce: {AdyenEx.Management.V1.NyceInfo, :t},
      paybybank_plaid: {AdyenEx.Management.V1.PayByBankPlaidInfo, :t},
      payme: {AdyenEx.Management.V1.PayMeInfo, :t},
      paypal: {AdyenEx.Management.V1.PayPalInfo, :t},
      payto: {AdyenEx.Management.V1.PayToInfo, :t},
      pulse: {AdyenEx.Management.V1.PulseInfo, :t},
      reference: :string,
      sepadirectdebit: {AdyenEx.Management.V1.SepaDirectDebitInfo, :t},
      shopperInteraction: {:enum, ["eCommerce", "pos", "moto", "contAuth"]},
      sodexo: {AdyenEx.Management.V1.SodexoInfo, :t},
      sofort: {AdyenEx.Management.V1.SofortInfo, :t},
      star: {AdyenEx.Management.V1.StarInfo, :t},
      storeId: :string,
      svs: {AdyenEx.Management.V1.SvsInfo, :t},
      swish: {AdyenEx.Management.V1.SwishInfo, :t},
      ticket: {AdyenEx.Management.V1.TicketInfo, :t},
      twint: {AdyenEx.Management.V1.TwintInfo, :t},
      type:
        {:enum,
         [
           "abrapetite",
           "abrapetite_credit",
           "abrapetite_debit",
           "abrapetite_prepaid",
           "accel",
           "ach",
           "affirm",
           "afterpaytouch",
           "alelo",
           "alipay",
           "alipay_hk",
           "alipay_plus",
           "alipay_plus_alipay_cn",
           "alipay_plus_alipay_hk",
           "alipay_plus_dana",
           "alipay_plus_gcash",
           "alipay_plus_kakaopay",
           "alipay_plus_kplus",
           "alipay_plus_naverpay",
           "alipay_plus_rabbitlinepay",
           "alipay_plus_tosspay",
           "alipay_plus_touchngo",
           "alipay_plus_truemoney",
           "alipay_wap",
           "amex",
           "applepay",
           "avancard",
           "avancard_credit",
           "avancard_debit",
           "banese_card",
           "banese_card_credit",
           "banese_card_debit",
           "banese_card_prepaid",
           "bcmc",
           "blik",
           "blik_pos",
           "br_schemes",
           "carnet",
           "cartebancaire",
           "cashapp",
           "clearpay",
           "clicktopay",
           "cooper",
           "cooper_credit",
           "cooper_debit",
           "cooper_food_debit",
           "cooper_meal_debit",
           "cooper_prepaid",
           "cooper_private_credit",
           "cooper_retail_credit",
           "credtodos",
           "credtodos_private_credit",
           "credtodos_private_debit",
           "cup",
           "diners",
           "directdebit_GB",
           "discover",
           "ebanking_FI",
           "eft_directdebit_CA",
           "eftpos_australia",
           "elo",
           "elocredit",
           "elodebit",
           "girocard",
           "givex",
           "googlepay",
           "green_card",
           "green_card_credit",
           "green_card_debit",
           "green_card_food_prepaid",
           "green_card_meal_prepaid",
           "green_card_prepaid",
           "hiper",
           "hipercard",
           "ideal",
           "interac_card",
           "jcb",
           "klarna",
           "klarna_account",
           "klarna_b2b",
           "klarna_paynow",
           "le_card",
           "le_card_credit",
           "le_card_debit",
           "maestro",
           "maestro_usa",
           "maxifrota",
           "maxifrota_prepaid",
           "mbway",
           "mc",
           "mcdebit",
           "mealVoucher_FR",
           "megaleve",
           "megaleve_credit",
           "megaleve_debit",
           "mobilepay",
           "multibanco",
           "nutricash",
           "nutricash_prepaid",
           "nyce",
           "onlineBanking_PL",
           "paybybank",
           "paybybank_plaid",
           "payme",
           "payme_pos",
           "paynow",
           "paynow_pos",
           "paypal",
           "payto",
           "personal_card",
           "personal_card_credit",
           "personal_card_debit",
           "pulse",
           "romcard",
           "romcard_credit",
           "romcard_debit",
           "senff",
           "senff_credit",
           "sepadirectdebit",
           "sodexo",
           "star",
           "svs",
           "swish",
           "ticket",
           "todo_giftcard",
           "trustly",
           "twint",
           "twint_pos",
           "up_brazil",
           "up_brazil_credit",
           "up_brazil_debit",
           "up_brazil_prepaid",
           "vale_refeicao",
           "vale_refeicao_prepaid",
           "valuelink",
           "vegas_card",
           "vegas_card_credit",
           "vegas_card_debit",
           "vero_card",
           "vero_card_credit",
           "vero_card_debit",
           "vero_card_prepaid",
           "vipps",
           "visa",
           "visadebit",
           "vpay",
           "wechatpay",
           "wechatpay_pos"
         ]},
      valuelink: {AdyenEx.Management.V1.ValuelinkInfo, :t},
      vipps: {AdyenEx.Management.V1.VippsInfo, :t},
      visa: {AdyenEx.Management.V1.GenericPmWithTdiInfo, :t},
      wechatpay: {AdyenEx.Management.V1.WeChatPayInfo, :t},
      wechatpay_pos: {AdyenEx.Management.V1.WeChatPayPosInfo, :t}
    ]
  end
end
