defmodule Adyen.Transfer.V2.Transfer do
  @moduledoc """
  Provides struct and type for a Transfer
  """

  @type t :: %__MODULE__{
          amount: Adyen.Transfer.V2.Amount.t(),
          balanceAccountId: String.t() | nil,
          bank: Adyen.Transfer.V2.Bank.t() | nil,
          counterparty: Adyen.Transfer.V2.Counterparty.t(),
          description: String.t() | nil,
          direction: String.t() | nil,
          id: String.t() | nil,
          paymentInstrumentId: String.t() | nil,
          reason: String.t() | nil,
          reference: String.t() | nil,
          referenceForBeneficiary: String.t() | nil,
          status: String.t()
        }

  defstruct [
    :amount,
    :balanceAccountId,
    :bank,
    :counterparty,
    :description,
    :direction,
    :id,
    :paymentInstrumentId,
    :reason,
    :reference,
    :referenceForBeneficiary,
    :status
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount: {Adyen.Transfer.V2.Amount, :t},
      balanceAccountId: :string,
      bank: {Adyen.Transfer.V2.Bank, :t},
      counterparty: {Adyen.Transfer.V2.Counterparty, :t},
      description: :string,
      direction: {:enum, ["incoming", "outgoing"]},
      id: :string,
      paymentInstrumentId: :string,
      reason:
        {:enum,
         [
           "accountHierarchyNotActive",
           "amountLimitExceeded",
           "approvalExpired",
           "approved",
           "balanceAccountTemporarilyBlockedByTransactionRule",
           "counterpartyAccountBlocked",
           "counterpartyAccountClosed",
           "counterpartyAccountNotFound",
           "counterpartyAddressRequired",
           "counterpartyBankTimedOut",
           "counterpartyBankUnavailable",
           "declined",
           "declinedByTransactionRule",
           "directDebitNotSupported",
           "error",
           "notEnoughBalance",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "refusedByCounterpartyBank",
           "refusedByCustomer",
           "routeNotFound",
           "scaFailed",
           "schemeAdvice",
           "transferInstrumentDoesNotExist",
           "unknown"
         ]},
      reference: :string,
      referenceForBeneficiary: :string,
      status:
        {:enum,
         [
           "approvalPending",
           "atmWithdrawal",
           "atmWithdrawalReversalPending",
           "atmWithdrawalReversed",
           "authAdjustmentAuthorised",
           "authAdjustmentError",
           "authAdjustmentRefused",
           "authorised",
           "bankTransfer",
           "bankTransferPending",
           "booked",
           "bookingPending",
           "cancelled",
           "capturePending",
           "captureReversalPending",
           "captureReversed",
           "captured",
           "capturedExternally",
           "chargeback",
           "chargebackExternally",
           "chargebackPending",
           "chargebackReversalPending",
           "chargebackReversed",
           "credited",
           "depositCorrection",
           "depositCorrectionPending",
           "dispute",
           "disputeClosed",
           "disputeExpired",
           "disputeNeedsReview",
           "error",
           "expired",
           "failed",
           "fee",
           "feePending",
           "internalTransfer",
           "internalTransferPending",
           "invoiceDeduction",
           "invoiceDeductionPending",
           "manualCorrectionPending",
           "manuallyCorrected",
           "matchedStatement",
           "matchedStatementPending",
           "merchantPayin",
           "merchantPayinPending",
           "merchantPayinReversed",
           "merchantPayinReversedPending",
           "miscCost",
           "miscCostPending",
           "paymentCost",
           "paymentCostPending",
           "pendingApproval",
           "pendingExecution",
           "received",
           "refundPending",
           "refundReversalPending",
           "refundReversed",
           "refunded",
           "refundedExternally",
           "refused",
           "rejected",
           "reserveAdjustment",
           "reserveAdjustmentPending",
           "returned",
           "secondChargeback",
           "secondChargebackPending",
           "undefined"
         ]}
    ]
  end
end
