defmodule Adyen.Transfer.V4.TransferEvent do
  @moduledoc """
  Provides struct and type for a TransferEvent
  """

  @type t :: %__MODULE__{
          amount: Adyen.Transfer.V4.Amount.t() | nil,
          amountAdjustments: [Adyen.Transfer.V4.AmountAdjustment.t()] | nil,
          arn: String.t() | nil,
          bookingDate: DateTime.t() | nil,
          estimatedArrivalTime: DateTime.t() | nil,
          eventsData:
            [
              Adyen.Transfer.V4.InterchangeData.t()
              | Adyen.Transfer.V4.IssuingTransactionData.t()
              | Adyen.Transfer.V4.MerchantPurchaseData.t()
            ]
            | nil,
          externalReason: Adyen.Transfer.V4.ExternalReason.t() | nil,
          id: String.t() | nil,
          modification: Adyen.Transfer.V4.Modification.t() | nil,
          mutations: [Adyen.Transfer.V4.BalanceMutation.t()] | nil,
          originalAmount: Adyen.Transfer.V4.Amount.t() | nil,
          reason: String.t() | nil,
          status: String.t() | nil,
          trackingData:
            Adyen.Transfer.V4.ConfirmationTrackingData.t()
            | Adyen.Transfer.V4.EstimationTrackingData.t()
            | Adyen.Transfer.V4.InternalReviewTrackingData.t()
            | nil,
          transactionId: String.t() | nil,
          type: String.t() | nil,
          updateDate: DateTime.t() | nil,
          valueDate: DateTime.t() | nil
        }

  defstruct [
    :amount,
    :amountAdjustments,
    :arn,
    :bookingDate,
    :estimatedArrivalTime,
    :eventsData,
    :externalReason,
    :id,
    :modification,
    :mutations,
    :originalAmount,
    :reason,
    :status,
    :trackingData,
    :transactionId,
    :type,
    :updateDate,
    :valueDate
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount: {Adyen.Transfer.V4.Amount, :t},
      amountAdjustments: [{Adyen.Transfer.V4.AmountAdjustment, :t}],
      arn: :string,
      bookingDate: {:string, "date-time"},
      estimatedArrivalTime: {:string, "date-time"},
      eventsData: [
        union: [
          {Adyen.Transfer.V4.InterchangeData, :t},
          {Adyen.Transfer.V4.IssuingTransactionData, :t},
          {Adyen.Transfer.V4.MerchantPurchaseData, :t}
        ]
      ],
      externalReason: {Adyen.Transfer.V4.ExternalReason, :t},
      id: :string,
      modification: {Adyen.Transfer.V4.Modification, :t},
      mutations: [{Adyen.Transfer.V4.BalanceMutation, :t}],
      originalAmount: {Adyen.Transfer.V4.Amount, :t},
      reason:
        {:enum,
         [
           "accountHierarchyNotActive",
           "amountLimitExceeded",
           "approvalExpired",
           "approved",
           "avsDeclined",
           "balanceAccountTemporarilyBlockedByTransactionRule",
           "blockCard",
           "callReferral",
           "cancelled",
           "captureCard",
           "cardExpired",
           "cardholderAuthenticationRequired",
           "cashbackAmountExceedsLimit",
           "cavvDeclined",
           "contactlessFallback",
           "contactlessLimitReached",
           "counterpartyAccountBlocked",
           "counterpartyAccountClosed",
           "counterpartyAccountNotFound",
           "counterpartyAddressRequired",
           "counterpartyBankTimedOut",
           "counterpartyBankUnavailable",
           "cryptographicFailure",
           "cvcDeclined",
           "declined",
           "declinedByBapValidation",
           "declinedByTransactionRule",
           "declinedNonGeneric",
           "directDebitNotSupported",
           "doNotHonor",
           "domesticDebitTransactionNotAllowed",
           "duplicateTransmissionDetected",
           "error",
           "formatError",
           "fraud",
           "fraudCancelled",
           "honorWithId",
           "internalTimeout",
           "invalidAccount",
           "invalidAmount",
           "invalidAuthorizationLifeCycle",
           "invalidCard",
           "invalidExpiryDate",
           "invalidFromAccount",
           "invalidIssuer",
           "invalidMerchant",
           "invalidPin",
           "invalidToAccount",
           "invalidTransaction",
           "issuerSuspectedFraud",
           "lostCard",
           "mobilePinRequired",
           "noCheckingAccount",
           "noSavingsAccount",
           "not3dAuthenticated",
           "notEnoughBalance",
           "notSubmitted",
           "notSupported",
           "partiallyApproved",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "pinNotChanged",
           "pinRequired",
           "pinTriesExceeded",
           "pinValidationNotPossible",
           "purchaseAmountOnlyNoCashBack",
           "refusedByCounterpartyBank",
           "refusedByCustomer",
           "restrictedCard",
           "revocationOfAuth",
           "routeNotFound",
           "scaAuthenticationRequired",
           "scaFailed",
           "schemeAdvice",
           "securityViolation",
           "shopperCancelled",
           "stolenCard",
           "threedsDynamicLinkingMismatch",
           "transactionNotPermitted",
           "transferInstrumentDoesNotExist",
           "unableToRouteTransaction",
           "unknown",
           "withdrawalAmountExceeded",
           "withdrawalCountExceeded"
         ]},
      status:
        {:enum,
         [
           "approvalPending",
           "atmWithdrawal",
           "atmWithdrawalReversalPending",
           "atmWithdrawalReversed",
           "authAdjustmentAuthorised",
           "authAdjustmentError",
           "authAdjustmentRefused",
           "authorised",
           "bankTransfer",
           "bankTransferPending",
           "booked",
           "bookingPending",
           "cancelled",
           "capturePending",
           "captureReversalPending",
           "captureReversed",
           "captured",
           "capturedExternally",
           "chargeback",
           "chargebackExternally",
           "chargebackPending",
           "chargebackReversalPending",
           "chargebackReversed",
           "credited",
           "depositCorrection",
           "depositCorrectionPending",
           "dispute",
           "disputeClosed",
           "disputeExpired",
           "disputeNeedsReview",
           "error",
           "expired",
           "failed",
           "fee",
           "feePending",
           "interchangeAdjusted",
           "internalTransfer",
           "internalTransferPending",
           "invoiceDeduction",
           "invoiceDeductionPending",
           "manualCorrectionPending",
           "manuallyCorrected",
           "matchedStatement",
           "matchedStatementPending",
           "merchantPayin",
           "merchantPayinPending",
           "merchantPayinReversed",
           "merchantPayinReversedPending",
           "miscCost",
           "miscCostPending",
           "paymentCost",
           "paymentCostPending",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "received",
           "refundPending",
           "refundReversalPending",
           "refundReversed",
           "refunded",
           "refundedExternally",
           "refused",
           "rejected",
           "reserveAdjustment",
           "reserveAdjustmentPending",
           "returned",
           "reversed",
           "secondChargeback",
           "secondChargebackPending",
           "undefined"
         ]},
      trackingData:
        {:union,
         [
           {Adyen.Transfer.V4.ConfirmationTrackingData, :t},
           {Adyen.Transfer.V4.EstimationTrackingData, :t},
           {Adyen.Transfer.V4.InternalReviewTrackingData, :t}
         ]},
      transactionId: :string,
      type: {:enum, ["accounting", "tracing", "tracking"]},
      updateDate: {:string, "date-time"},
      valueDate: {:string, "date-time"}
    ]
  end
end
