defmodule Adyen.Transfer.V4.Transfer do
  @moduledoc """
  Provides struct and type for a Transfer
  """

  @type t :: %__MODULE__{
          accountHolder: Adyen.Transfer.V4.ResourceReference.t() | nil,
          amount: Adyen.Transfer.V4.Amount.t(),
          balanceAccount: Adyen.Transfer.V4.ResourceReference.t() | nil,
          category: String.t(),
          categoryData:
            Adyen.Transfer.V4.BankCategoryData.t()
            | Adyen.Transfer.V4.InternalCategoryData.t()
            | Adyen.Transfer.V4.IssuedCard.t()
            | Adyen.Transfer.V4.PlatformPayment.t()
            | nil,
          counterparty: Adyen.Transfer.V4.CounterpartyV3.t(),
          createdAt: DateTime.t() | nil,
          creationDate: DateTime.t() | nil,
          description: String.t() | nil,
          directDebitInformation: Adyen.Transfer.V4.DirectDebitInformation.t() | nil,
          direction: String.t() | nil,
          executionDate: Adyen.Transfer.V4.ExecutionDate.t() | nil,
          id: String.t() | nil,
          paymentInstrument: Adyen.Transfer.V4.PaymentInstrument.t() | nil,
          reason: String.t() | nil,
          reference: String.t() | nil,
          referenceForBeneficiary: String.t() | nil,
          review: Adyen.Transfer.V4.TransferReview.t() | nil,
          status: String.t(),
          type: String.t() | nil,
          ultimateParty: Adyen.Transfer.V4.UltimatePartyIdentification.t() | nil
        }

  defstruct [
    :accountHolder,
    :amount,
    :balanceAccount,
    :category,
    :categoryData,
    :counterparty,
    :createdAt,
    :creationDate,
    :description,
    :directDebitInformation,
    :direction,
    :executionDate,
    :id,
    :paymentInstrument,
    :reason,
    :reference,
    :referenceForBeneficiary,
    :review,
    :status,
    :type,
    :ultimateParty
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountHolder: {Adyen.Transfer.V4.ResourceReference, :t},
      amount: {Adyen.Transfer.V4.Amount, :t},
      balanceAccount: {Adyen.Transfer.V4.ResourceReference, :t},
      category: {:enum, ["bank", "card", "internal", "issuedCard", "platformPayment", "topUp"]},
      categoryData:
        {:union,
         [
           {Adyen.Transfer.V4.BankCategoryData, :t},
           {Adyen.Transfer.V4.InternalCategoryData, :t},
           {Adyen.Transfer.V4.IssuedCard, :t},
           {Adyen.Transfer.V4.PlatformPayment, :t}
         ]},
      counterparty: {Adyen.Transfer.V4.CounterpartyV3, :t},
      createdAt: {:string, "date-time"},
      creationDate: {:string, "date-time"},
      description: :string,
      directDebitInformation: {Adyen.Transfer.V4.DirectDebitInformation, :t},
      direction: {:enum, ["incoming", "outgoing"]},
      executionDate: {Adyen.Transfer.V4.ExecutionDate, :t},
      id: :string,
      paymentInstrument: {Adyen.Transfer.V4.PaymentInstrument, :t},
      reason:
        {:enum,
         [
           "accountHierarchyNotActive",
           "amountLimitExceeded",
           "approvalExpired",
           "approved",
           "avsDeclined",
           "balanceAccountTemporarilyBlockedByTransactionRule",
           "blockCard",
           "callReferral",
           "cancelled",
           "captureCard",
           "cardExpired",
           "cardholderAuthenticationRequired",
           "cashbackAmountExceedsLimit",
           "cavvDeclined",
           "contactlessFallback",
           "contactlessLimitReached",
           "counterpartyAccountBlocked",
           "counterpartyAccountClosed",
           "counterpartyAccountNotFound",
           "counterpartyAddressRequired",
           "counterpartyBankTimedOut",
           "counterpartyBankUnavailable",
           "cryptographicFailure",
           "cvcDeclined",
           "declined",
           "declinedByBapValidation",
           "declinedByTransactionRule",
           "declinedNonGeneric",
           "directDebitNotSupported",
           "doNotHonor",
           "domesticDebitTransactionNotAllowed",
           "duplicateTransmissionDetected",
           "error",
           "formatError",
           "fraud",
           "fraudCancelled",
           "honorWithId",
           "internalTimeout",
           "invalidAccount",
           "invalidAmount",
           "invalidAuthorizationLifeCycle",
           "invalidCard",
           "invalidExpiryDate",
           "invalidFromAccount",
           "invalidIssuer",
           "invalidMerchant",
           "invalidPin",
           "invalidToAccount",
           "invalidTransaction",
           "issuerSuspectedFraud",
           "lostCard",
           "mobilePinRequired",
           "noCheckingAccount",
           "noSavingsAccount",
           "not3dAuthenticated",
           "notEnoughBalance",
           "notSubmitted",
           "notSupported",
           "partiallyApproved",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "pinNotChanged",
           "pinRequired",
           "pinTriesExceeded",
           "pinValidationNotPossible",
           "purchaseAmountOnlyNoCashBack",
           "refusedByCounterpartyBank",
           "refusedByCustomer",
           "restrictedCard",
           "revocationOfAuth",
           "routeNotFound",
           "scaAuthenticationRequired",
           "scaFailed",
           "schemeAdvice",
           "securityViolation",
           "shopperCancelled",
           "stolenCard",
           "threedsDynamicLinkingMismatch",
           "transactionNotPermitted",
           "transferInstrumentDoesNotExist",
           "unableToRouteTransaction",
           "unknown",
           "withdrawalAmountExceeded",
           "withdrawalCountExceeded"
         ]},
      reference: :string,
      referenceForBeneficiary: :string,
      review: {Adyen.Transfer.V4.TransferReview, :t},
      status:
        {:enum,
         [
           "approvalPending",
           "atmWithdrawal",
           "atmWithdrawalReversalPending",
           "atmWithdrawalReversed",
           "authAdjustmentAuthorised",
           "authAdjustmentError",
           "authAdjustmentRefused",
           "authorised",
           "bankTransfer",
           "bankTransferPending",
           "booked",
           "bookingPending",
           "cancelled",
           "capturePending",
           "captureReversalPending",
           "captureReversed",
           "captured",
           "capturedExternally",
           "chargeback",
           "chargebackExternally",
           "chargebackPending",
           "chargebackReversalPending",
           "chargebackReversed",
           "credited",
           "depositCorrection",
           "depositCorrectionPending",
           "dispute",
           "disputeClosed",
           "disputeExpired",
           "disputeNeedsReview",
           "error",
           "expired",
           "failed",
           "fee",
           "feePending",
           "interchangeAdjusted",
           "internalTransfer",
           "internalTransferPending",
           "invoiceDeduction",
           "invoiceDeductionPending",
           "manualCorrectionPending",
           "manuallyCorrected",
           "matchedStatement",
           "matchedStatementPending",
           "merchantPayin",
           "merchantPayinPending",
           "merchantPayinReversed",
           "merchantPayinReversedPending",
           "miscCost",
           "miscCostPending",
           "paymentCost",
           "paymentCostPending",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "received",
           "refundPending",
           "refundReversalPending",
           "refundReversed",
           "refunded",
           "refundedExternally",
           "refused",
           "rejected",
           "reserveAdjustment",
           "reserveAdjustmentPending",
           "returned",
           "reversed",
           "secondChargeback",
           "secondChargebackPending",
           "undefined"
         ]},
      type:
        {:enum,
         [
           "payment",
           "capture",
           "captureReversal",
           "refund",
           "refundReversal",
           "chargeback",
           "chargebackCorrection",
           "chargebackReversal",
           "chargebackReversalCorrection",
           "secondChargeback",
           "secondChargebackCorrection",
           "atmWithdrawal",
           "atmWithdrawalReversal",
           "internalTransfer",
           "internalDirectDebit",
           "manualCorrection",
           "invoiceDeduction",
           "depositCorrection",
           "reserveAdjustment",
           "bankTransfer",
           "bankDirectDebit",
           "cardTransfer",
           "miscCost",
           "paymentCost",
           "fee",
           "leftover",
           "grant",
           "capitalFundsCollection",
           "cashOutInstruction",
           "cashoutFee",
           "cashoutRepayment",
           "cashoutFunding",
           "repayment",
           "installment",
           "installmentReversal",
           "balanceAdjustment",
           "balanceRollover",
           "balanceMigration"
         ]},
      ultimateParty: {Adyen.Transfer.V4.UltimatePartyIdentification, :t}
    ]
  end
end
