defmodule Adyen.Checkout.V46.Donations do
  @moduledoc """
  Provides API endpoint related to donations
  """

  @default_client Adyen.Client

  @doc """
  Make a donation

  Takes in the donation token generated by the `/payments` request and uses it to make the donation.

  For more information, see [Donations](https://docs.adyen.com/online-payments/donations).

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec post_donations(body :: Adyen.Checkout.V46.DonationPaymentRequest.t(), opts :: keyword) ::
          {:ok, Adyen.Checkout.V46.DonationPaymentResponse.t()}
          | {:error, Adyen.Checkout.V46.ServiceError.t()}
  def post_donations(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {Adyen.Checkout.V46.Donations, :post_donations},
      url: "/donations",
      body: body,
      method: :post,
      request: [{"application/json", {Adyen.Checkout.V46.DonationPaymentRequest, :t}}],
      response: [
        {200, {Adyen.Checkout.V46.DonationPaymentResponse, :t}},
        {400, {Adyen.Checkout.V46.ServiceError, :t}},
        {401, {Adyen.Checkout.V46.ServiceError, :t}},
        {403, {Adyen.Checkout.V46.ServiceError, :t}},
        {422, {Adyen.Checkout.V46.ServiceError, :t}},
        {500, {Adyen.Checkout.V46.ServiceError, :t}}
      ],
      opts: opts
    })
  end
end
