defmodule AdyenEx.Checkout.V69.PaymentLinkRequest do
  @moduledoc """
  Provides struct and type for a PaymentLinkRequest
  """

  @type t :: %__MODULE__{
          allowedPaymentMethods: [String.t()] | nil,
          amount: AdyenEx.Checkout.V69.Amount.t(),
          applicationInfo: AdyenEx.Checkout.V69.ApplicationInfo.t() | nil,
          billingAddress: AdyenEx.Checkout.V69.Address.t() | nil,
          blockedPaymentMethods: [String.t()] | nil,
          captureDelayHours: integer | nil,
          countryCode: String.t() | nil,
          dateOfBirth: Date.t() | nil,
          deliverAt: DateTime.t() | nil,
          deliveryAddress: AdyenEx.Checkout.V69.Address.t() | nil,
          description: String.t() | nil,
          expiresAt: String.t() | nil,
          fundOrigin: AdyenEx.Checkout.V69.FundOrigin.t() | nil,
          fundRecipient: AdyenEx.Checkout.V69.FundRecipient.t() | nil,
          installmentOptions: map | nil,
          lineItems: [AdyenEx.Checkout.V69.LineItem.t()] | nil,
          manualCapture: boolean | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          metadata: map | nil,
          platformChargebackLogic: AdyenEx.Checkout.V69.PlatformChargebackLogic.t() | nil,
          recurringProcessingModel: String.t() | nil,
          reference: String.t(),
          requiredShopperFields: [String.t()] | nil,
          returnUrl: String.t() | nil,
          reusable: boolean | nil,
          riskData: AdyenEx.Checkout.V69.RiskData.t() | nil,
          shopperEmail: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: AdyenEx.Checkout.V69.Name.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          showRemovePaymentMethodButton: boolean | nil,
          socialSecurityNumber: String.t() | nil,
          splitCardFundingSources: boolean | nil,
          splits: [AdyenEx.Checkout.V69.Split.t()] | nil,
          store: String.t() | nil,
          storePaymentMethodMode: String.t() | nil,
          telephoneNumber: String.t() | nil,
          themeId: String.t() | nil,
          threeDS2RequestData: AdyenEx.Checkout.V69.CheckoutSessionThreeDs2RequestData.t() | nil
        }

  defstruct [
    :allowedPaymentMethods,
    :amount,
    :applicationInfo,
    :billingAddress,
    :blockedPaymentMethods,
    :captureDelayHours,
    :countryCode,
    :dateOfBirth,
    :deliverAt,
    :deliveryAddress,
    :description,
    :expiresAt,
    :fundOrigin,
    :fundRecipient,
    :installmentOptions,
    :lineItems,
    :manualCapture,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :metadata,
    :platformChargebackLogic,
    :recurringProcessingModel,
    :reference,
    :requiredShopperFields,
    :returnUrl,
    :reusable,
    :riskData,
    :shopperEmail,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :showRemovePaymentMethodButton,
    :socialSecurityNumber,
    :splitCardFundingSources,
    :splits,
    :store,
    :storePaymentMethodMode,
    :telephoneNumber,
    :themeId,
    :threeDS2RequestData
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      allowedPaymentMethods: [:string],
      amount: {AdyenEx.Checkout.V69.Amount, :t},
      applicationInfo: {AdyenEx.Checkout.V69.ApplicationInfo, :t},
      billingAddress: {AdyenEx.Checkout.V69.Address, :t},
      blockedPaymentMethods: [:string],
      captureDelayHours: {:integer, "int32"},
      countryCode: :string,
      dateOfBirth: {:string, "date"},
      deliverAt: {:string, "date-time"},
      deliveryAddress: {AdyenEx.Checkout.V69.Address, :t},
      description: :string,
      expiresAt: :string,
      fundOrigin: {AdyenEx.Checkout.V69.FundOrigin, :t},
      fundRecipient: {AdyenEx.Checkout.V69.FundRecipient, :t},
      installmentOptions: :map,
      lineItems: [{AdyenEx.Checkout.V69.LineItem, :t}],
      manualCapture: :boolean,
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      metadata: :map,
      platformChargebackLogic: {AdyenEx.Checkout.V69.PlatformChargebackLogic, :t},
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      reference: :string,
      requiredShopperFields: [
        enum: [
          "billingAddress",
          "deliveryAddress",
          "shopperEmail",
          "shopperName",
          "telephoneNumber"
        ]
      ],
      returnUrl: :string,
      reusable: :boolean,
      riskData: {AdyenEx.Checkout.V69.RiskData, :t},
      shopperEmail: :string,
      shopperLocale: :string,
      shopperName: {AdyenEx.Checkout.V69.Name, :t},
      shopperReference: :string,
      shopperStatement: :string,
      showRemovePaymentMethodButton: :boolean,
      socialSecurityNumber: :string,
      splitCardFundingSources: :boolean,
      splits: [{AdyenEx.Checkout.V69.Split, :t}],
      store: :string,
      storePaymentMethodMode: {:enum, ["askForConsent", "disabled", "enabled"]},
      telephoneNumber: :string,
      themeId: :string,
      threeDS2RequestData: {AdyenEx.Checkout.V69.CheckoutSessionThreeDs2RequestData, :t}
    ]
  end
end
