defmodule AdyenEx.Checkout.V50.BalanceCheckRequest do
  @moduledoc """
  Provides struct and type for a BalanceCheckRequest
  """

  @type t :: %__MODULE__{
          accountInfo: AdyenEx.Checkout.V50.AccountInfo.t() | nil,
          additionalAmount: AdyenEx.Checkout.V50.Amount.t() | nil,
          additionalData: map | nil,
          amount: AdyenEx.Checkout.V50.Amount.t(),
          applicationInfo: AdyenEx.Checkout.V50.ApplicationInfo.t() | nil,
          billingAddress: AdyenEx.Checkout.V50.Address.t() | nil,
          browserInfo: AdyenEx.Checkout.V50.BrowserInfo.t() | nil,
          captureDelayHours: integer | nil,
          dateOfBirth: Date.t() | nil,
          dccQuote: AdyenEx.Checkout.V50.ForexQuote.t() | nil,
          deliveryAddress: AdyenEx.Checkout.V50.Address.t() | nil,
          deliveryDate: DateTime.t() | nil,
          deviceFingerprint: String.t() | nil,
          fraudOffset: integer | nil,
          installments: AdyenEx.Checkout.V50.Installments.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          merchantRiskIndicator: AdyenEx.Checkout.V50.MerchantRiskIndicator.t() | nil,
          metadata: map | nil,
          orderReference: String.t() | nil,
          paymentMethod: map,
          recurring: AdyenEx.Checkout.V50.Recurring.t() | nil,
          recurringProcessingModel: String.t() | nil,
          reference: String.t() | nil,
          selectedBrand: String.t() | nil,
          selectedRecurringDetailReference: String.t() | nil,
          sessionId: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: AdyenEx.Checkout.V50.Name.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          socialSecurityNumber: String.t() | nil,
          splits: [AdyenEx.Checkout.V50.Split.t()] | nil,
          store: String.t() | nil,
          telephoneNumber: String.t() | nil,
          threeDS2RequestData: AdyenEx.Checkout.V50.ThreeDs2RequestData.t() | nil,
          threeDSAuthenticationOnly: boolean | nil,
          totalsGroup: String.t() | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :amount,
    :applicationInfo,
    :billingAddress,
    :browserInfo,
    :captureDelayHours,
    :dateOfBirth,
    :dccQuote,
    :deliveryAddress,
    :deliveryDate,
    :deviceFingerprint,
    :fraudOffset,
    :installments,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :merchantRiskIndicator,
    :metadata,
    :orderReference,
    :paymentMethod,
    :recurring,
    :recurringProcessingModel,
    :reference,
    :selectedBrand,
    :selectedRecurringDetailReference,
    :sessionId,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :socialSecurityNumber,
    :splits,
    :store,
    :telephoneNumber,
    :threeDS2RequestData,
    :threeDSAuthenticationOnly,
    :totalsGroup,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {AdyenEx.Checkout.V50.AccountInfo, :t},
      additionalAmount: {AdyenEx.Checkout.V50.Amount, :t},
      additionalData: :map,
      amount: {AdyenEx.Checkout.V50.Amount, :t},
      applicationInfo: {AdyenEx.Checkout.V50.ApplicationInfo, :t},
      billingAddress: {AdyenEx.Checkout.V50.Address, :t},
      browserInfo: {AdyenEx.Checkout.V50.BrowserInfo, :t},
      captureDelayHours: {:integer, "int32"},
      dateOfBirth: {:string, "date"},
      dccQuote: {AdyenEx.Checkout.V50.ForexQuote, :t},
      deliveryAddress: {AdyenEx.Checkout.V50.Address, :t},
      deliveryDate: {:string, "date-time"},
      deviceFingerprint: :string,
      fraudOffset: {:integer, "int32"},
      installments: {AdyenEx.Checkout.V50.Installments, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      merchantRiskIndicator: {AdyenEx.Checkout.V50.MerchantRiskIndicator, :t},
      metadata: :map,
      orderReference: :string,
      paymentMethod: :map,
      recurring: {AdyenEx.Checkout.V50.Recurring, :t},
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      reference: :string,
      selectedBrand: :string,
      selectedRecurringDetailReference: :string,
      sessionId: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {AdyenEx.Checkout.V50.Name, :t},
      shopperReference: :string,
      shopperStatement: :string,
      socialSecurityNumber: :string,
      splits: [{AdyenEx.Checkout.V50.Split, :t}],
      store: :string,
      telephoneNumber: :string,
      threeDS2RequestData: {AdyenEx.Checkout.V50.ThreeDs2RequestData, :t},
      threeDSAuthenticationOnly: :boolean,
      totalsGroup: :string,
      trustedShopper: :boolean
    ]
  end
end
