defmodule AdyenEx.Management.V3.ClientCertificatesCompanyLevel do
  @moduledoc """
  Provides API endpoints related to client certificates company level
  """

  @default_client AdyenEx.Client

  @doc """
  Retrieve all valid client certificates for this company

  Retrieve all previously issued client certificates under this company account which are still valid (neither expired nor revoked).

  To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):
  * Management API - Client certificates read

  """
  @spec get_companies_company_id_client_certificates(companyId :: String.t(), opts :: keyword) ::
          {:ok, AdyenEx.Management.V3.CertificateSearchResponse.t()}
          | {:error, AdyenEx.Management.V3.DefaultErrorResponseEntity.t()}
  def get_companies_company_id_client_certificates(companyId, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [companyId: companyId],
      call:
        {AdyenEx.Management.V3.ClientCertificatesCompanyLevel,
         :get_companies_company_id_client_certificates},
      url: "/companies/#{companyId}/clientCertificates",
      method: :get,
      response: [
        {200, {AdyenEx.Management.V3.CertificateSearchResponse, :t}},
        {401, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {403, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {429, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {500, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}}
      ],
      opts: opts
    })
  end

  @doc """
  Generate a client certificate

  Generates a client certificate for secure communication with Adyen using mutual TLS (mTLS). Provide a certificate signing request (CSR). Adyen signs it and returns the client certificate.

  The CSR must be generated by a key pair that meets the following criteria:
  * Key ownership: the CSR must be signed by the associated private key.
  * Key type: RSA with a minimum key size of 2048 bits, or ECC with a minimum key size of 224 bits.

  A company account can have a maximum of 10 valid client certificates at a time.

  The subject distinguished name (`subjectDN`) of the issued certificate is constructed by Adyen from the path `companyId` and the request `apiCredential`. The subject in your CSR is not used. The returned `subjectDN` has the format `UID={apiCredential}-Company.{companyId},CN={apiCredential}-Company.{companyId},O=Company.{companyId}`.

  To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):
  * Management API - Client certificates read and write

  ## Request Body

  **Content Types**: `application/json`

  Certificate signing request details.
  """
  @spec post_companies_company_id_client_certificates(
          companyId :: String.t(),
          body :: AdyenEx.Management.V3.ClientCertificateRequest.t(),
          opts :: keyword
        ) ::
          {:ok, AdyenEx.Management.V3.ClientCertificateWithChain.t()}
          | {:error, AdyenEx.Management.V3.DefaultErrorResponseEntity.t()}
  def post_companies_company_id_client_certificates(companyId, body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [companyId: companyId, body: body],
      call:
        {AdyenEx.Management.V3.ClientCertificatesCompanyLevel,
         :post_companies_company_id_client_certificates},
      url: "/companies/#{companyId}/clientCertificates",
      body: body,
      method: :post,
      request: [{"application/json", {AdyenEx.Management.V3.ClientCertificateRequest, :t}}],
      response: [
        {201, {AdyenEx.Management.V3.ClientCertificateWithChain, :t}},
        {400, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {401, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {403, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {422, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {429, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}},
        {500, {AdyenEx.Management.V3.DefaultErrorResponseEntity, :t}}
      ],
      opts: opts
    })
  end
end
