defmodule Adyen.Management.V3.PaymentMethodResponse do
  @moduledoc """
  Provides struct and type for a PaymentMethodResponse
  """

  @type t :: %__MODULE__{
          _links: Adyen.Management.V3.PaginationLinks.t() | nil,
          data: [Adyen.Management.V3.PaymentMethod.t()] | nil,
          itemsTotal: integer,
          pagesTotal: integer,
          typesWithErrors: [String.t()] | nil
        }

  defstruct [:_links, :data, :itemsTotal, :pagesTotal, :typesWithErrors]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      _links: {Adyen.Management.V3.PaginationLinks, :t},
      data: [{Adyen.Management.V3.PaymentMethod, :t}],
      itemsTotal: {:integer, "int32"},
      pagesTotal: {:integer, "int32"},
      typesWithErrors: [
        enum: [
          "abrapetite",
          "abrapetite_credit",
          "abrapetite_debit",
          "abrapetite_prepaid",
          "accel",
          "ach",
          "affirm",
          "afterpaytouch",
          "alelo",
          "alipay",
          "alipay_hk",
          "alipay_plus",
          "alipay_plus_alipay_cn",
          "alipay_plus_alipay_hk",
          "alipay_plus_dana",
          "alipay_plus_gcash",
          "alipay_plus_kakaopay",
          "alipay_plus_kplus",
          "alipay_plus_naverpay",
          "alipay_plus_rabbitlinepay",
          "alipay_plus_tosspay",
          "alipay_plus_touchngo",
          "alipay_plus_truemoney",
          "alipay_wap",
          "amex",
          "applepay",
          "avancard",
          "avancard_credit",
          "avancard_debit",
          "banese_card",
          "banese_card_credit",
          "banese_card_debit",
          "banese_card_prepaid",
          "bcmc",
          "blik",
          "blik_pos",
          "br_schemes",
          "carnet",
          "cartebancaire",
          "clearpay",
          "clicktopay",
          "cooper",
          "cooper_credit",
          "cooper_debit",
          "cooper_food_debit",
          "cooper_meal_debit",
          "cooper_prepaid",
          "cooper_private_credit",
          "cooper_retail_credit",
          "credtodos",
          "credtodos_private_credit",
          "credtodos_private_debit",
          "cup",
          "diners",
          "directdebit_GB",
          "discover",
          "ebanking_FI",
          "eft_directdebit_CA",
          "eftpos_australia",
          "elo",
          "elocredit",
          "elodebit",
          "girocard",
          "givex",
          "googlepay",
          "green_card",
          "green_card_credit",
          "green_card_debit",
          "green_card_food_prepaid",
          "green_card_meal_prepaid",
          "green_card_prepaid",
          "hiper",
          "hipercard",
          "ideal",
          "interac_card",
          "jcb",
          "klarna",
          "klarna_account",
          "klarna_b2b",
          "klarna_paynow",
          "le_card",
          "le_card_credit",
          "le_card_debit",
          "maestro",
          "maestro_usa",
          "maxifrota",
          "maxifrota_prepaid",
          "mbway",
          "mc",
          "mcdebit",
          "mealVoucher_FR",
          "megaleve",
          "megaleve_credit",
          "megaleve_debit",
          "mobilepay",
          "multibanco",
          "nutricash",
          "nutricash_prepaid",
          "nyce",
          "onlineBanking_PL",
          "paybybank",
          "paybybank_plaid",
          "payme",
          "payme_pos",
          "paynow",
          "paynow_pos",
          "paypal",
          "payto",
          "personal_card",
          "personal_card_credit",
          "personal_card_debit",
          "pulse",
          "romcard",
          "romcard_credit",
          "romcard_debit",
          "senff",
          "senff_credit",
          "sepadirectdebit",
          "sodexo",
          "star",
          "svs",
          "swish",
          "ticket",
          "todo_giftcard",
          "trustly",
          "twint",
          "twint_pos",
          "up_brazil",
          "up_brazil_credit",
          "up_brazil_debit",
          "up_brazil_prepaid",
          "vale_refeicao",
          "vale_refeicao_prepaid",
          "valuelink",
          "vegas_card",
          "vegas_card_credit",
          "vegas_card_debit",
          "vero_card",
          "vero_card_credit",
          "vero_card_debit",
          "vero_card_prepaid",
          "vipps",
          "visa",
          "visadebit",
          "vpay",
          "wechatpay",
          "wechatpay_pos"
        ]
      ]
    ]
  end
end
