defmodule AdyenEx.Management.V3.PaymentMethod do
  @moduledoc """
  Provides struct and type for a PaymentMethod
  """

  @type t :: %__MODULE__{
          accel: AdyenEx.Management.V3.AccelResponseInfo.t() | nil,
          affirm: AdyenEx.Management.V3.AffirmResponseInfo.t() | nil,
          afterpayTouch: AdyenEx.Management.V3.AfterpayTouchResponseInfo.t() | nil,
          alipayPlus: AdyenEx.Management.V3.AlipayPlusResponseInfo.t() | nil,
          allowed: boolean | nil,
          amex: AdyenEx.Management.V3.AmexResponseInfo.t() | nil,
          applePay: AdyenEx.Management.V3.ApplePayResponseInfo.t() | nil,
          associatedPaymentMethods: [AdyenEx.Management.V3.AssociatedPaymentMethod.t()] | nil,
          bcmc: AdyenEx.Management.V3.BcmcResponseInfo.t() | nil,
          businessLineId: String.t() | nil,
          carnet: AdyenEx.Management.V3.CarnetResponseInfo.t() | nil,
          cartesBancaires: AdyenEx.Management.V3.CartesBancairesResponseInfo.t() | nil,
          clearpay: AdyenEx.Management.V3.ClearpayResponseInfo.t() | nil,
          countries: [String.t()] | nil,
          cup: AdyenEx.Management.V3.CupResponseInfo.t() | nil,
          currencies: [String.t()] | nil,
          customRoutingFlags: [String.t()] | nil,
          diners: AdyenEx.Management.V3.DinersResponseInfo.t() | nil,
          discover: AdyenEx.Management.V3.DiscoverResponseInfo.t() | nil,
          eft_directdebit_CA: AdyenEx.Management.V3.EFTDirectDebitCAResponseInfo.t() | nil,
          eftpos_australia: AdyenEx.Management.V3.EftPosAustraliaResponseInfo.t() | nil,
          enabled: boolean | nil,
          girocard: AdyenEx.Management.V3.GirocardResponseInfo.t() | nil,
          givex: AdyenEx.Management.V3.GivexResponseInfo.t() | nil,
          googlePay: AdyenEx.Management.V3.GooglePayResponseInfo.t() | nil,
          id: String.t(),
          ideal: AdyenEx.Management.V3.IdealResponseInfo.t() | nil,
          interac_card: AdyenEx.Management.V3.InteracCardResponseInfo.t() | nil,
          jcb: AdyenEx.Management.V3.JCBResponseInfo.t() | nil,
          klarna: AdyenEx.Management.V3.KlarnaResponseInfo.t() | nil,
          maestro: AdyenEx.Management.V3.MaestroResponseInfo.t() | nil,
          maestro_usa: AdyenEx.Management.V3.MaestroUSAResponseInfo.t() | nil,
          mc: AdyenEx.Management.V3.MCResponseInfo.t() | nil,
          mealVoucher_FR: AdyenEx.Management.V3.MealVoucherFRResponseInfo.t() | nil,
          nyce: AdyenEx.Management.V3.NyceResponseInfo.t() | nil,
          paybybank_plaid: AdyenEx.Management.V3.PayByBankPlaidResponseInfo.t() | nil,
          payme: AdyenEx.Management.V3.PayMeResponseInfo.t() | nil,
          paypal: AdyenEx.Management.V3.PayPalResponseInfo.t() | nil,
          payto: AdyenEx.Management.V3.PayToResponseInfo.t() | nil,
          pulse: AdyenEx.Management.V3.PulseResponseInfo.t() | nil,
          reference: String.t() | nil,
          sepadirectdebit: AdyenEx.Management.V3.SepaDirectDebitResponseInfo.t() | nil,
          shopperInteraction: String.t() | nil,
          sodexo: AdyenEx.Management.V3.SodexoResponseInfo.t() | nil,
          sofort: AdyenEx.Management.V3.SofortResponseInfo.t() | nil,
          star: AdyenEx.Management.V3.StarResponseInfo.t() | nil,
          storeIds: [String.t()] | nil,
          svs: AdyenEx.Management.V3.SvsResponseInfo.t() | nil,
          swish: AdyenEx.Management.V3.SwishResponseInfo.t() | nil,
          ticket: AdyenEx.Management.V3.TicketResponseInfo.t() | nil,
          twint: AdyenEx.Management.V3.TwintResponseInfo.t() | nil,
          type: String.t() | nil,
          valuelink: AdyenEx.Management.V3.ValuelinkResponseInfo.t() | nil,
          verificationStatus: String.t() | nil,
          vipps: AdyenEx.Management.V3.VippsResponseInfo.t() | nil,
          visa: AdyenEx.Management.V3.VisaResponseInfo.t() | nil,
          wechatpay: AdyenEx.Management.V3.WeChatPayResponseInfo.t() | nil,
          wechatpay_pos: AdyenEx.Management.V3.WeChatPayPosResponseInfo.t() | nil
        }

  defstruct [
    :accel,
    :affirm,
    :afterpayTouch,
    :alipayPlus,
    :allowed,
    :amex,
    :applePay,
    :associatedPaymentMethods,
    :bcmc,
    :businessLineId,
    :carnet,
    :cartesBancaires,
    :clearpay,
    :countries,
    :cup,
    :currencies,
    :customRoutingFlags,
    :diners,
    :discover,
    :eft_directdebit_CA,
    :eftpos_australia,
    :enabled,
    :girocard,
    :givex,
    :googlePay,
    :id,
    :ideal,
    :interac_card,
    :jcb,
    :klarna,
    :maestro,
    :maestro_usa,
    :mc,
    :mealVoucher_FR,
    :nyce,
    :paybybank_plaid,
    :payme,
    :paypal,
    :payto,
    :pulse,
    :reference,
    :sepadirectdebit,
    :shopperInteraction,
    :sodexo,
    :sofort,
    :star,
    :storeIds,
    :svs,
    :swish,
    :ticket,
    :twint,
    :type,
    :valuelink,
    :verificationStatus,
    :vipps,
    :visa,
    :wechatpay,
    :wechatpay_pos
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accel: {AdyenEx.Management.V3.AccelResponseInfo, :t},
      affirm: {AdyenEx.Management.V3.AffirmResponseInfo, :t},
      afterpayTouch: {AdyenEx.Management.V3.AfterpayTouchResponseInfo, :t},
      alipayPlus: {AdyenEx.Management.V3.AlipayPlusResponseInfo, :t},
      allowed: :boolean,
      amex: {AdyenEx.Management.V3.AmexResponseInfo, :t},
      applePay: {AdyenEx.Management.V3.ApplePayResponseInfo, :t},
      associatedPaymentMethods: [{AdyenEx.Management.V3.AssociatedPaymentMethod, :t}],
      bcmc: {AdyenEx.Management.V3.BcmcResponseInfo, :t},
      businessLineId: :string,
      carnet: {AdyenEx.Management.V3.CarnetResponseInfo, :t},
      cartesBancaires: {AdyenEx.Management.V3.CartesBancairesResponseInfo, :t},
      clearpay: {AdyenEx.Management.V3.ClearpayResponseInfo, :t},
      countries: [:string],
      cup: {AdyenEx.Management.V3.CupResponseInfo, :t},
      currencies: [:string],
      customRoutingFlags: [:string],
      diners: {AdyenEx.Management.V3.DinersResponseInfo, :t},
      discover: {AdyenEx.Management.V3.DiscoverResponseInfo, :t},
      eft_directdebit_CA: {AdyenEx.Management.V3.EFTDirectDebitCAResponseInfo, :t},
      eftpos_australia: {AdyenEx.Management.V3.EftPosAustraliaResponseInfo, :t},
      enabled: :boolean,
      girocard: {AdyenEx.Management.V3.GirocardResponseInfo, :t},
      givex: {AdyenEx.Management.V3.GivexResponseInfo, :t},
      googlePay: {AdyenEx.Management.V3.GooglePayResponseInfo, :t},
      id: :string,
      ideal: {AdyenEx.Management.V3.IdealResponseInfo, :t},
      interac_card: {AdyenEx.Management.V3.InteracCardResponseInfo, :t},
      jcb: {AdyenEx.Management.V3.JCBResponseInfo, :t},
      klarna: {AdyenEx.Management.V3.KlarnaResponseInfo, :t},
      maestro: {AdyenEx.Management.V3.MaestroResponseInfo, :t},
      maestro_usa: {AdyenEx.Management.V3.MaestroUSAResponseInfo, :t},
      mc: {AdyenEx.Management.V3.MCResponseInfo, :t},
      mealVoucher_FR: {AdyenEx.Management.V3.MealVoucherFRResponseInfo, :t},
      nyce: {AdyenEx.Management.V3.NyceResponseInfo, :t},
      paybybank_plaid: {AdyenEx.Management.V3.PayByBankPlaidResponseInfo, :t},
      payme: {AdyenEx.Management.V3.PayMeResponseInfo, :t},
      paypal: {AdyenEx.Management.V3.PayPalResponseInfo, :t},
      payto: {AdyenEx.Management.V3.PayToResponseInfo, :t},
      pulse: {AdyenEx.Management.V3.PulseResponseInfo, :t},
      reference: :string,
      sepadirectdebit: {AdyenEx.Management.V3.SepaDirectDebitResponseInfo, :t},
      shopperInteraction: :string,
      sodexo: {AdyenEx.Management.V3.SodexoResponseInfo, :t},
      sofort: {AdyenEx.Management.V3.SofortResponseInfo, :t},
      star: {AdyenEx.Management.V3.StarResponseInfo, :t},
      storeIds: [:string],
      svs: {AdyenEx.Management.V3.SvsResponseInfo, :t},
      swish: {AdyenEx.Management.V3.SwishResponseInfo, :t},
      ticket: {AdyenEx.Management.V3.TicketResponseInfo, :t},
      twint: {AdyenEx.Management.V3.TwintResponseInfo, :t},
      type: :string,
      valuelink: {AdyenEx.Management.V3.ValuelinkResponseInfo, :t},
      verificationStatus: {:enum, ["valid", "pending", "invalid", "rejected"]},
      vipps: {AdyenEx.Management.V3.VippsResponseInfo, :t},
      visa: {AdyenEx.Management.V3.VisaResponseInfo, :t},
      wechatpay: {AdyenEx.Management.V3.WeChatPayResponseInfo, :t},
      wechatpay_pos: {AdyenEx.Management.V3.WeChatPayPosResponseInfo, :t}
    ]
  end
end
